config/routes.rb
Rails.application.routes.draw do
  resources :nominees
  resources :awards
  get 'static_pages/about'
  devise_for :users
  root "awards#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  has_many :nominees, dependent: :destroy
  validates_presence_of :name, :description
end

app/models/nominee.rb
class Nominee < ApplicationRecord
  belongs_to :award

  validates_presence_of :first_name, :last_name, :biography
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :authenticate_user!
  def index
    @awards = Award.all
  end

  def new
    @award = Award.new
  end

  def show
    @award = Award.find_by(id: params[:id])
  end

  def create
    @award = Award.new(awards_params)

    if @award.save
      flash[:notice] = "Created an Award"
      redirect_to @award
    else
      render :new
    end
  end

  private
  def awards_params
    params.require(:award).permit(:name, :description, :image)
  end

end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController
  before_action :authenticate_user!
  def index
    @nominees =Nominee.all
  end

  def show
    @nominee = Nominee.find(params[:id])
  end

  def new
    @nominee = Nominee.new
    @awards = Award.all
  end

  def create
    @nominee = Nominee.new(nominees_params)
    @nominee.award_id = params[:award]

    if @nominee.save
      flash[:notice] = "Created an Award"
      redirect_to @nominee
    else
      render :new
    end
  end

  private
  def nominees_params
    params.require(:nominee).permit(:first_name, :last_name, :biography, :video, :image)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/awards/_form.html.erb
<div class="ui center aligned container" style="width:60%">
  <div class="ui container">
    <div class="ui segment">
    <%= form_for @award, html: {class: "ui form"}, method: :post, class: "ui form",  multipart: true do |f| %>
  <ul>
  <% @award.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="field" style="font-size: 1.3em;">
    <%= f.label :name%><br />
    <%= f.text_field :name, required: true, placeholder: "Input a descriptive title" %>
  </div>

  <div class="field" style="font-size: 1.3em;">
    <%= f.label :description%><br />
    <%= f.text_area :description, required: true, placeholder: "Add a good description" %>
  </div>
  <div class="field">
    <%= f.file_field "image", required: true, class: "ui button", accept: "image/*"%>
  </div>
  <p>
    <%= f.submit "Create Article", class: "ui primary button", style: "font-size: 1.2em;"%>
  </p>
  
<% end %>
</div>

</div>
</div>

app/views/awards/index.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment" >
    <%= link_to "Create new award", new_award_path, class: "floating ui purple tag label"%>
    <span class="ui huge header">CATEGORIES</span>
  </div>
  <div class="ui container">
    <div class="ui segment">
        <div class="ui link centered cards">
          <%@awards.each do |award|%>
           <%= link_to award_path(award) do %>
              <div class="ui card">
                <div class="image">
                  <%= image_tag("lolx.jfif", class: "ui rounded image") %>
                </div>
                  <%= link_to "#{award.name}", award_path(award), class: "ui basic huge bottom attached label"%>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/awards/new.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment">
    <h2 class="ui huge header">ADD CATEGORY</h2>
  </div>
  <%= render partial: 'form'%>
</div>

app/views/awards/show.html.erb
<div id="content">
  <div class="ui container">
    <div class="ui center aligned segment">
      <h2 class="huge header"><%= @award.name.upcase %></h2>
    </div>
    <div class="ui placeholder stacked segment">
      <div class="ui two column stackable center aligned grid">
        <div class="ui vertical divider"><i class="massive trophy icon"></i></div>
        <div class="middle aligned row">
          <div class="column">
            <div class="ui medium image">
                <%= image_tag("lolx.jfif", class: "ui image") %>
            </div>
          </div>
          <div class="column">
            <h2>Description</h2>
            <div class="ui icon header">
              <%= @award.description.upcase %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="ui center aligned container" style="width: 60%;">
      <div class="ui segment">
        <h3>Nominees</h3>
      </div>
      <div class="ui small sequenced images">
        <% @award.nominees.each do |nominee|%>
          <%= link_to nominee_path(nominee) do%>
          <%= image_tag("lolx.jfif", class: "ui circular image ") %>
          <% end %>
        <% end %>
      </div>
    </div>
    
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<script>
  
  $('.sequenced.images .image').hover().transition({
    debug     : true,
        animation : 'jiggle',
        duration  : 500,
        interval  : 200
  });

</script>

app/views/layouts/_errors.html.erb
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<div class="ui vertical footer segment">
<div class="ui center aligned container">
  <i class="big facebook icon"></i>
  <i class="big instagram icon"></i>
  <i class="big twitter icon"></i>
  <i class="big youtube icon"></i>
</div>
</div>

app/views/layouts/_javascript.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<script>
  $(document).ready(function() {
    $(".ui.toggle.button").click(function() {
      let menu = $(this)
        .parent()
        .parent()
        .parent();
      $(".ui.vertical.menu", menu).toggle(100);
    });

    $(".ui.dropdown").dropdown();

    $(".ui.progress").progress({
      showActivity: false
    });
  });
</script>

app/views/layouts/_navbar.html.erb
<div class="ui tablet computer only padded grid">
  <div class="ui inverted top fixed  large borderless menu">
    <div class="ui container">
      <%= link_to "Awards", awards_path, class: "active header item"%>
      <%= link_to "Home", awards_path, class: "item"%>
      <%= link_to "Nominees", nominees_path, class: "item" %>
      <%= link_to "About", static_pages_about_path, class: "item" %>

    <div class="right menu">
      <div class="item">
        <div class="ui icon input">
          <input type="text" placeholder="Search...">
          <i class="search link icon"></i>
        </div>
      </div>
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "ui item"%>
      <%else%>
        <div class="ui item">
          <%= link_to "Login", new_user_session_path, class: "ui inverted blue button"%>
        </div>
        <div class="ui item">
          <%= link_to "SignUp", new_user_registration_path, class: "ui pink inverted button"%>
        </div>
        
      <% end %>
      
    </div>
</div>

  </div>
</div>

<div class="ui mobile only grid">
  <div class="ui inverted top fixed borderless menu">
    <%= link_to "Awards", awards_path, class: "header item"%>
    <div class="right menu">
      <div class="item">
        <button class="ui icon toggle basic inverted button">
          <i class="content icon"></i>
        </button>
      </div>
    </div>
    <div class="ui inverted vertical borderless fluid menu">
      <%= link_to "Home", awards_path, class: "item"%>
      <%= link_to "Nominees", nominees_path, class: "item" %>
      <%= link_to "About", static_pages_about_path, class: "item" %>
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, class: "ui item"%>
      <%else%>
        <div class="ui item">
          <%= link_to "Login", new_user_session_path, class: "ui inverted blue primary button"%>
        </div>
        <div class="ui item">
          <%= link_to "SignUp", new_user_registration_path, class: "ui pink inverted button"%>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no"
    />
    <meta
      name="description"
      content="Semantic-UI-Forest, collection of design, themes and templates for Semantic-UI."
    />
    <meta name="keywords" content="Semantic-UI, Theme, Design, Template" />
    <title>Theme Template for Semantic-UI</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render partial: 'layouts/navbar'%>
    <%= render partial: 'layouts/errors'%>
    
    <div id="content">
      <%= yield %>
    </div>
    
  </body>

  <%= render 'layouts/footer' %>
  <%= render 'layouts/javascript' %>
  
</html>

app/views/nominees/_form.html.erb
<div class="ui center aligned container" style="width:60%">
  <div class="ui container">
    <div class="ui segment">
    <%= form_for @nominee, html: {class: "ui form"}, method: :post, class: "ui form",  multipart: true do |f| %>
  <ul>
  <% @nominee.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="field">
    <% if @awards%>
      <label>Select Award</label>
      <select class="ui dropdown" name="award" required= "true">                          
          <option value="">Select Award</option>
        <% @awards.each do |award| %>                    
          <option value="<%= award.id %>"><%= award.name %></option>                                    
        <% end %>
      </select>
    <% else %>                  
      <label>No Awards Created</label>
    <% end %>
  </div>
  <div class="field" style="font-size: 1.3em;">
    <%= f.label :first_name%><br />
    <%= f.text_field :first_name, required: true, placeholder: "First Name", autofocus: true %>
  </div>
  <div class="field" style="font-size: 1.3em;">
    <%= f.label :last_name%><br />
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>

  <div class="field" style="font-size: 1.3em;">
    <%= f.label :biography%><br />
    <%= f.text_area :biography, required: true, placeholder: "Add a biography" %>
  </div>
  <div class="field">
    <%= f.file_field "video", class: "ui button", accept: "image/*"%>
  </div>
  <p>
    <%= f.submit "Nominate", class: "ui primary button", style: "font-size: 1.2em;"%>
  </p>
  
<% end %>
</div>

</div>
</div>

app/views/nominees/index.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment" style="background-image: linear-gradient(to right, rgb(128, 88, 15), rgb(107, 107, 184), rgb(108, 202, 108));">
    <%= link_to "Create new Nominee", new_nominee_path, class: "floating ui purple tag label"%>
    <span class="ui huge header">NOMINEES</span>
  </div>
  <div class="ui center aligned container" style="width: 50%">
    <%@nominees.each do |nominee|%>
      <div class="ui segment">
        <div class="ui vertical divider"><i class="info icon"></i></div>
        <div class="ui two column grid">
          <%= link_to nominee_path(nominee), class: "column" do %>
            <div class="ui small stretched image">
              <%= image_tag("lolx.jfif", class: "ui rounded image") %>
            </div>
          <% end %>
          <%= link_to nominee_path(nominee), class: "column" do %>
          <div class="column" style="color: black;">
            <h2 class="header"><%= "#{nominee.first_name.upcase} #{nominee.last_name.upcase}"%></h2>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">category</h5>
            <h3 class="header"><%= nominee.award.name.upcase%></h3>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/nominees/new.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment">
    <h2 class="ui huge header">ADD NOMINEE</h2>
  </div>
  <%= render partial: 'form'%>
</div>

app/views/nominees/show.html.erb
<div id="content">
  <div class="ui container">
    <div class="ui center aligned segment">
      <h2 class="huge inverted header">Nominated for the
        <span >
          <%= link_to @nominee.award.name.upcase, award_path(@nominee.award)%>
        </span>
        award</h2>
    </div>
    <div class="ui center aligned container">
      <div class="ui three column stackable center aligned grid">
        <div class="column">
          <div class="ui segment">
              <h4 class="header" style="text-decoration: underline;">name</h4>
              <h1><%= @nominee.first_name%> <%= @nominee.last_name%></h1>
          </div>
        </div>
        <div class="column">
          <div class="ui segment">
              <div class="ui slide masked reveal">
                <%= image_tag("lolx.jfif", class: "visible content")%>
                <%= image_tag("lolx.jfif", class: "hidden content")%>
              </div>
          </div>
        </div>
        <div class="column">
          <div class="ui segment">
            <h4 class="header" style="text-decoration: underline;">Biography</h4>
          <h1>
            <%= @nominee.biography%>
          </h1>
          </div>
        </div>
      </div>
      <!-- <div class="ui center aligned placeholder piled segment">
        <div class="ui left dividing rail">
          <h1 class="ui container" style="background-color: red; margin-top: 50%">
            <p><%= @nominee.first_name%> <%= @nominee.last_name%></p>
          </h1>
        </div>
        <div class="ui  right dividing rail">
          <h4 class="header" style="text-decoration: underline;">Biography</h4>
          <h1>
            <%= @nominee.biography%>
          </h1>
          
        </div>
        <div class="ui card" >
          <div class="ui slide masked reveal">
            <%= image_tag("lolx.jfif", class: "visible content")%>
            <%= image_tag("lolx.jfif", class: "hidden content")%>
          </div>
        </div>
      </div> -->
    </div>
  </div> 
</div>

app/views/static_pages/about.html.erb
<div id="content">
  <div class="ui container">
    <div class="ui jumbotron message">
      <div class="ui huge header">Template Name</div>
      <p>
        Description:
        This is a template showcasing the optional theme stylesheet included
        in Semantic-UI. Use it as a starting point to create something more
        unique by building on or modifying it.
      </p>
    </div>
    <div class="ui center aligned container">
      <h2 class="ui huge header">Authors</h2>
      <div class="ui medium sequenced images">
        <%= image_tag("elyse.png", class: "ui circular image ") %>
        <%= image_tag("elyse.png", class: "ui circular image") %>
        <%= image_tag("elyse.png", class: "ui circular image") %>
      </div>
    </div>
    
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<script>
  
  $('.sequenced.images .image').hover().transition({
    debug     : true,
        animation : 'jiggle',
        duration  : 500,
        interval  : 200
  });

</script>